- name: See if configurations is a directory (then we nuke it next)
  shell: "[ -d {{ openhab_configuration_dir  }}] && echo 'Directory' || echo ''"
  register: is_directory

- name: create openHAB configrations directories
  file: path={{ openhab_configuration_dir}}/{{ item }} state=directory
  become: true
  become_user: openhab
  become_method: sudo
  with_items:
    - persistence
    - icons/classic
    - items
    - transform
    - rules
    - scripts
    - sitemaps
    - services
    - html
    - icon
    - sounds
    - things

    
# ok with "sudo ansible-playbook  playbook.yml  -i hosts  -K -vvvv  --connection=local  --ask-sudo-pass"
# Example of copy command with setting mode for the file
# - copy: src={{ item }} dest={{ openhab_configuration_dir }}/persistence owner='openhab' group='openhab' mode=0755
- copy: src={{ item }} dest={{ openhab_configuration_dir }}/persistence owner='openhab' group='openhab'
  with_fileglob:
    - ../templates/configurations/persistence/*

# Example of copy command with ansible name for the task
- name: Copy content of dir icons/classic
  copy: src={{ item }} dest={{ openhab_configuration_dir }}/icons/classic owner='openhab' group='openhab'
  with_fileglob:
    - ../templates/configurations/icons/classic/*

- copy: src={{ item }} dest={{ openhab_configuration_dir }}/items owner='openhab' group='openhab'
  with_fileglob:
    - ../templates/configurations/items/*

- copy: src={{ item }} dest={{ openhab_configuration_dir }}/transform owner='openhab' group='openhab'
  with_fileglob:
    - ../templates/configurations/transform/*

- copy: src={{ item }} dest={{ openhab_configuration_dir }}/rules owner='openhab' group='openhab'
  with_fileglob:
    - ../templates/configurations/rules/*

- copy: src={{ item }} dest={{ openhab_configuration_dir }}/scripts owner='openhab' group='openhab'
  with_fileglob:
    - ../templates/configurations/scripts/*

- copy: src={{ item }} dest={{ openhab_configuration_dir }}/sitemaps owner='openhab' group='openhab'
  with_fileglob:
    - ../templates/configurations/sitemaps/*

- copy: src={{ item }} dest={{ openhab_configuration_dir }}/services owner='openhab' group='openhab'
  with_fileglob:
    - ../templates/configurations/services/*

- copy: src={{ item }} dest={{ openhab_configuration_dir }}/html owner='openhab' group='openhab'
  with_fileglob:
    - ../templates/configurations/html/*

- copy: src={{ item }} dest={{ openhab_configuration_dir }}/icon owner='openhab' group='openhab'
  with_fileglob:
    - ../templates/configurations/icon/*

- copy: src={{ item }} dest={{ openhab_configuration_dir }}/sounds owner='openhab' group='openhab'
  with_fileglob:
    - ../templates/configurations/sounds/*

- copy: src={{ item }} dest={{ openhab_configuration_dir }}/things owner='openhab' group='openhab'
  with_fileglob:
    - ../templates/configurations/things/*



- name: sync openhab java opts
  become: yes
  template: dest="/etc/default/openhab2" src="../templates/openhab2"



    
# - name: Your copy task
#   copy: src={{ item.src }} dest={{ item.dest }}
#   become_user: openhab
#   become_method: sudo
#   with_items:
#     - { src: '../templates/configurations/icons/classic/readme.txt', dest: '{{ openhab_configuration_dir }}/icons/classic/readme.txt' }
#     - { src: '../templates/configurations/icons/classic/analytics_8_icon.png', dest: '{{ openhab_configuration_dir }}/icons/classic/analytics_8_icon.png' }






# - name: sync setup into config
#   template: dest={{ openhab_configuration_dir }}/{{item}} src=../templates/configurations/{{item}}
#   become: yes
#   become_user: openhab
#   with_items:
#     - persistence/readme.txt
#     - persistence/rrd4j.persist
#     - icons/classic/readme.txt
#     - icons/classic/analytics_8_icon.png
# ...
    

